# escape=`

FROM octopuslabs/workertools:latest-windows.2022
SHELL ["powershell", "-Command"]

# Install Terraform
RUN choco install git -y --no-progress

# Install Terraform
RUN choco install terraform -y --no-progress